Lavaland remap
SinguloStation13/SinguloStation13 pull request #42
Opened 2022-09-23 01:00 UTC by nogoodidea

## About The Pull Request

Removes lavaland mineing base.

## Why It's Good For The Game
muh lore. it's a construction server i want to build a mineing base.

## Changelog
:cl:
del: lavaland mineing base
/:cl:

2022-09-23 01:01 UTC, nogoodidea commented
hmmm well this pushed the tesla coil changes too
ummmmmmmmm hold on

2022-09-23 02:49 UTC, MaltVinegar requested changes

2022-09-23 02:49 UTC, MaltVinegar commented on code/modules/power/singularity/collector.dm
> +			SSresearch.science_tech.add_point_type(TECHWEB_POINT_TYPE_DISCOVERY, bitcoins_mined*RAD_COLLECTOR_MINING_CONVERSION_RATE) // Singlo edit - makes rad collectors gen discovery points
When the

2022-09-30 20:26 UTC, nogoodidea commented
allright 8 days later i fixed it,YAY

2022-10-06 00:42 UTC, MaltVinegar approved these changes

2022-10-06 00:42 UTC, merged